# Generated by Django 2.1.5 on 2019-03-14 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190313_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='assessment_counter',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='assessment_list',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
