# Generated by Django 2.1.5 on 2019-03-15 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_bank_assessment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='assessment_count',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
